[package]
name = "check-crates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.155", features = ["derive"]}
serde_json = "1.0.94"
reqwest = {version="0.11.14", features=["blocking"]}
clap = {version="4.1.8", features=["cargo"]}